BEGIN;

ALTER TABLE brands
  ADD COLUMN IF NOT EXISTS email VARCHAR NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS website VARCHAR NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS instagram VARCHAR NOT NULL DEFAULT '';

ALTER TABLE past_collaborations
  ADD COLUMN IF NOT EXISTS campaign_type VARCHAR NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS estimated_reach INT DEFAULT 0,
  ADD COLUMN IF NOT EXISTS outcome_tag VARCHAR DEFAULT 'neutral';

ALTER TABLE influencers DROP CONSTRAINT IF EXISTS fk_influencers_audience_age_group;
ALTER TABLE influencers DROP CONSTRAINT IF EXISTS fk_influencers_audience_gender;

COMMIT;
