version: '3.8'

services:
  back:
    build: .
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
  ds:
    build: ../ds
    container_name: ds
    depends_on:
      - back
    volumes:
      - ../ds:/workspace
      - .:/backend
    working_dir: /workspace
    command: python src/eda_modeling.py
