version: '3.8'

services:
  back:
    build: .
    container_name: back
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    environment:
      - ENVIRONMENT=development
  front:
    build: ../front
    container_name: front
    ports:
      - "8501:8501"
    volumes:
      - ../front:/app
